<template>
  <z-space :size="[20, 30]">
    <z-button>按钮</z-button>
    <z-button>按钮</z-button>
    <z-button>按钮</z-button>
    <z-button>按钮</z-button>
    <z-button>按钮</z-button>
    <z-button>按钮</z-button>
    <z-button>按钮</z-button>
    <z-button>按钮</z-button>
    <z-button>按钮</z-button>
    <z-button>按钮</z-button>
    <z-button>按钮</z-button>
    <z-button>按钮</z-button>
    <z-button>按钮</z-button>
    <z-button>按钮</z-button>
    <z-button>按钮</z-button>
    <z-button>按钮</z-button>
  </z-space>
</template>
